# Configuration for Yeoman Jekyll project

name: <%= appname %>
description: <%= jekDescript %>

# author :
#   name       : <%= author %>
#   email      : <%= email %>
#   github     : <%= github %>

# Custom paths
source:      .
destination: ./_site
plugins:     ./_plugins

# Grunt handles compiling and reloading Jekyll
server: false
auto: false

# Exclude files from compilation
# Excludes .dot and _underscore files and directories by default
exclude: ['bower.json', 'Gruntfile.js', 'package.json', 'config.rb', 'readme.md', 'travis.yml']

# Force inclusion of files that would otherwise be excluded
include: ['.htaccess']

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: <%= jekPost %>

# Publish posts with future date.
# The _config.build.yml file sets this to false on grunt build
future: true

# Compile posts in the _drafts directory.
# The _config.build.yml file sets this to false on grunt build
show_drafts: true

<% if (jekPage !== 'all') { %># Split posts over multiple subdirectories called “page2”, “page3”, … “pageN”
paginate: <%= jekPage %>
paginate_path: 'page:num'<% } %>

# Markdown library
markdown: <%= jekMkd %>
# Markdown library options<% if (jekMkd === 'maruku') { %>
# maruku:
  # use_tex:    false
  # use_divs:   false
  # png_engine: blahtex
  # png_dir:    images/latex
  # png_url:    /images/latex<% } %><% if (jekMkd === 'rdiscount') {%>
# rdiscount:
  # extensions: []<% } %><% if (jekMkd === 'kramdown') {%>
# kramdown:
  # auto_ids: true
  # footnote_nr: 1
  # entity_output: as_char
  # toc_levels: 1..6
  # use_coderay: false
  # coderay:
  #   coderay_wrap: div
  #   coderay_line_numbers: inline
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: style<% } %><% if (jekMkd === 'redcarpet') {%>
# redcarpet:
  # extensions: [ fenced_code_blocks, smart ]<% } %>

# Use Pygments to highlight code blocks
pygments: <%= jekPyg %>
